newsletter/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('newsletter.views',
    # admin stuff
    url(
        regex=r'^email_users/$',
        view='email_users',
        name='email_users'),
    url(
        regex=r'^email_users/(?P<message_id>\d+)/$',
        view='email_users',
        name='email_users'),
    url(
        regex=r'^email_delete/(?P<id>\d+)/$',
        view='email_delete',
        name='email_delete'),
)

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
from django.conf import settings
from core.views import resend_activation_email, contact_us
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(regex=r'^$',
        view='core.views.index',
        name='index'),
    url(regex=r'^contact_us/$',
        view=contact_us,
        name='contact_us'),
    url(regex=r'^contact/sent/$',
        view='django.views.generic.simple.direct_to_template',
        name='message_sent',
        kwargs={'template': 'core/message_sent.html'}),
    url(regex=r'^logout/$',
        view='django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/'}),
    url(regex=r'^resend_activation_email/$',
        view=resend_activation_email,
        name='resend_activation_email'),
    url(regex=r'^tos/$',
        view='django.views.generic.simple.direct_to_template',
        name='tos',
        kwargs={'template': 'tos.html'}),
    url(regex=r'^changelog/$',
        view='django.views.generic.simple.direct_to_template',
        name='changelog',
        kwargs={'template': 'changelog.html'}),
    url(r'^home/', include('core.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^issues/', include('bugtracker.urls')),
    url(r'^user/', include('registration_urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backup/', include('backup.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^forum/', include('forum.urls')),


)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

newsletter/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _

USER_TYPE_SUBSCRIPTION_PAID = 1
USER_TYPE_SUBSCRIPTION_TRIAL = 2
USER_TYPE_SUBSCRIPTION_EXPIRED = 3
USER_TYPE = ((USER_TYPE_SUBSCRIPTION_PAID, _('Users who have paid subscription')),
             (USER_TYPE_SUBSCRIPTION_TRIAL, _('Users still in trial')),
             (USER_TYPE_SUBSCRIPTION_EXPIRED, _('Users with subscription expired')))

class Message(models.Model):
    to = models.IntegerField(verbose_name=_('User type'), choices=USER_TYPE)
    subject = models.CharField(verbose_name=_('Subject'), max_length=100)
    message = models.TextField(verbose_name=_('Message'), help_text=_('Signature will be automatically added'))
    update_datetime = models.DateTimeField(verbose_name=_('Update date'))
    sent = models.BooleanField(verbose_name=_('Sent'), default=False)

    class Meta:
        ordering = ['-update_datetime']

newsletter/forms.py
from django import forms
from newsletter.models import Message

class EmailUsersForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['update_datetime']

    def __init__(self, *args, **kwargs):
        super(EmailUsersForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'mail-subject'

newsletter/views.py
from django.contrib.admin.views.decorators import staff_member_required
from newsletter.forms import EmailUsersForm
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from newsletter.models import Message
from django.db.transaction import commit_on_success
import datetime

@staff_member_required
@commit_on_success
def email_users(request, message_id=None):
    message_list = Message.objects.all()

    message = None
    if message_id:
        message = get_object_or_404(Message, pk=message_id)

    if request.method == 'POST':
        form = EmailUsersForm(request.POST, instance=message)
        if form.is_valid():
            message = form.save(commit=False)
            message.update_datetime = datetime.datetime.now()
            message.save()
            messages.success(request, _('Message stored successfully for later sending.'))
            return redirect(reverse('email_users'))
    else:
        form = EmailUsersForm(instance=message)
    return render_to_response('newsletter/email_users.html',
                              {'title': _('Email users'),
                               'form': form,
                               'message_list': message_list},
                              context_instance=RequestContext(request))

@staff_member_required
@commit_on_success
def email_delete(request, id):
    message = get_object_or_404(Message, pk=id)

    if request.method == 'POST':
        if request.POST.get('delete'):
            message.delete()
            messages.success(request, _('The message has been deleted successfully'))
            return redirect(reverse('email_users'))
        else:
            return redirect(reverse('email_users'))

    return render_to_response('delete.html',
                              {'active': 'account',
                               'title': _('Delete the message'),
                               'object_label': _('the message "%(subject)s"') % {'subject': message.subject}},
                               context_instance=RequestContext(request))

templates/newsletter/email_users.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form action="" method="post" id="email-users-form">
    {% csrf_token %}
    <fieldset class="module aligned">
    {% with form as form %}
    {% include "form.html" %}
    {% endwith %}
    </fieldset>
    <div class="submit-row">
    <input class="default" type="submit" name="action" value="{% trans "Save" %}" />
    </div>
</form>

{% if message_list %}
<div class="search-list">
    <table>
        <thead>
            <tr>
                <th>{% trans "To" %}</th>
                <th>{% trans "Subject" %}</th>
                <th>{% trans "Update date" %}</th>
                <th>{% trans "Sent" %}</th>
                <th>{% trans "Action" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for message in message_list %}
           <tr class="{% cycle 'row1' 'row2' %}">
                <td><a href="{% url email_users message.id %}">{{ message.get_to_display }}</a></td>
                <td><a href="{% url email_users message.id %}">{{ message.subject }}</a></td>
                <td><a href="{% url email_users message.id %}">{{ message.update_datetime }}</a></td>
                <td><a href="{% url email_users message.id %}">{% if message.sent %}{% trans "yes" %}{% else %}{% trans "no" %}{% endif %}</a></td>
                <td><a href="{% url email_delete message.id %}">{% trans "delete" %}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
{% trans "No messages" %}
{% endif %}
{% endblock %}

templates/newsletter/signature.html
L'équipe {{ site.name }}

Vous recevez cet email car vous êtes inscrit(e) sur https://{{ site }}. Si vous voulez quitter le site, veuillez cliquer sur le lien ci-dessous pour vous désinscrire. Attention, si vous avez un abonnement, celui-ci sera perdu.
https://{{ site }}{% url unregister %}