core/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('core.views',
    url(regex=r'^$',
        view='settings_edit',
        name='settings_edit'),
    url(regex=r'^logo_overview/$',
        view='logo_overview',
        name='logo_overview'),
    url(regex=r'^logo_delete/$',
        view='logo_delete',
        name='logo_delete'),
    url(regex=r'^change_password/$',
        view='change_password',
        name='change_password'),
    url(regex=r'^subscribe/$',
        view='subscribe',
        name='subscribe'),
    url(regex=r'^subscription_paid/$',
        view='subscription_paid',
        name='subscription_paid'),
    url(regex=r'^paypal_ipn/$',
        view='paypal_ipn',
        name='paypal_ipn'),
    url(regex=r'^unregister/$',
        view='unregister',
        name='unregister'),
    url(regex=r'^admin_dashboard/$',
        view='admin_dashboard',
        name='admin_dashboard'),
)

urlpatterns = urlpatterns + patterns('notification.views',
    # notifications
    url(regex=r'^notifications/$',
        view='notification_edit',
        name='notification_edit'),
)

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
from django.conf import settings
from core.views import resend_activation_email, contact_us
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(regex=r'^$',
        view='core.views.index',
        name='index'),
    url(regex=r'^contact_us/$',
        view=contact_us,
        name='contact_us'),
    url(regex=r'^contact/sent/$',
        view='django.views.generic.simple.direct_to_template',
        name='message_sent',
        kwargs={'template': 'core/message_sent.html'}),
    url(regex=r'^logout/$',
        view='django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/'}),
    url(regex=r'^resend_activation_email/$',
        view=resend_activation_email,
        name='resend_activation_email'),
    url(regex=r'^tos/$',
        view='django.views.generic.simple.direct_to_template',
        name='tos',
        kwargs={'template': 'tos.html'}),
    url(regex=r'^changelog/$',
        view='django.views.generic.simple.direct_to_template',
        name='changelog',
        kwargs={'template': 'changelog.html'}),
    url(r'^home/', include('core.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^issues/', include('bugtracker.urls')),
    url(r'^user/', include('registration_urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backup/', include('backup.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^forum/', include('forum.urls')),


)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

core/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models
from django.contrib.auth.models import User

class OwnedObject(models.Model):
    owner = models.ForeignKey(User)
    uuid = models.CharField(max_length=36, unique=True, default=uuid.uuid4)

    def save(self, force_insert=False, force_update=False, using=None, user=None):
        if user:
            owner_set = True
            try:
                self.owner
            except User.DoesNotExist:
                owner_set = False

            if not (user.is_superuser and owner_set):
                self.owner = user

        if not self.uuid:
            self.uuid = uuid.uuid4()

        super(OwnedObject, self).save(force_insert, force_update, using)

core/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import PasswordInput
from django.utils.translation import ugettext_lazy as _
from registration.forms import RegistrationFormUniqueEmail
from django.contrib.sites.models import Site

class UserForm(ModelForm):
    first_name = forms.CharField(label=_('first name'), max_length=30)
    last_name = forms.CharField(label=_('last name'), max_length=30)

    class Meta:
        model = User
        fields = ['first_name', 'last_name']

class PasswordForm(forms.Form):
    current_password = forms.CharField(label=_('Current password'), widget=PasswordInput(render_value=False))
    new_password = forms.CharField(label=_('New password'), widget=PasswordInput(render_value=False))
    retyped_new_password = forms.CharField(label=_('Retype password'), widget=PasswordInput(render_value=False))

    def clean(self):
        cleaned_data = self.cleaned_data
        new_password = cleaned_data.get("new_password")
        retyped_new_password = cleaned_data.get("retyped_new_password")

        if new_password <> retyped_new_password:
            self._errors["retyped_new_password"] = self.error_class([_("Password doesn't match")])
            del cleaned_data['retyped_new_password']

        return cleaned_data

class RegistrationFormUniqueEmailAndTos(RegistrationFormUniqueEmail):
    tos = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'required'}),
                             label=_(u'I have read and agree to the Terms of Service'),
                             error_messages={'required': _("You must agree to the terms to register")})

    def __init__(self, *args, **kwargs):
        super(RegistrationFormUniqueEmailAndTos, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = _('only letters, numbers and underscores are accepted')
        # only to override a missing translation in django-registration
        self.fields['username'].error_messages['invalid'] = _("This value must contain only letters, numbers and underscores.")
        self.fields['email'].help_text = _('must be valid to activate your account')

    def clean_username(self):
        """
        Validate that the username is different from "demo"
        to protect demo account
        """
        super(RegistrationFormUniqueEmailAndTos, self).clean_username()
        if self.cleaned_data['username'] == 'demo':
            raise forms.ValidationError(_("A user with that username already exists."))
        return self.cleaned_data['username']

class ResendActivationEmailForm(forms.Form):
    email = forms.EmailField(label=_('Email'), widget=forms.TextInput(attrs={'class': 'required',
                                                                             'maxlength':75}))

class ContactUsForm(forms.Form):
    name = forms.CharField(label=_('Name'), max_length=50)
    email = forms.EmailField(label=_('Email'))
    subject = forms.CharField(label=_('Subject'))
    message = forms.CharField(label=_('Message'), widget=forms.Textarea())

    def __init__(self, *args, **kwargs):
        super(ContactUsForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'mail-subject'

core/views.py
import logging
from decimal import Decimal
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext, Context
from django.utils.translation import ugettext_lazy as _, ugettext
from core.forms import UserForm, PasswordForm, ResendActivationEmailForm, \
    ContactUsForm
from autoentrepreneur.forms import UserProfileForm
from contact.forms import AddressForm
from django.db.transaction import commit_on_success
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from accounts.models import Expense, Invoice, INVOICE_STATE_PAID, \
    PAYMENT_TYPE_BANK_CARD, InvoiceRow
from core.decorators import settings_required, disabled_for_demo
from autoentrepreneur.models import AUTOENTREPRENEUR_ACTIVITY_PRODUCT_SALE_BIC, \
    Subscription, SUBSCRIPTION_STATE_NOT_PAID, SUBSCRIPTION_STATE_PAID, \
    SUBSCRIPTION_STATE_TRIAL, UserProfile
from project.models import Proposal, Project, PROJECT_STATE_FINISHED, \
    PROPOSAL_STATE_BALANCED, ROW_CATEGORY_SERVICE, ProposalRow, VAT_RATES_19_6
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from autoentrepreneur.decorators import subscription_required
from django.contrib.auth import logout
from django.core.mail import mail_admins
from announcement.models import Announcement
from contact.models import Contact, CONTACT_TYPE_COMPANY, Address
from django.contrib.sites.models import Site
from django.http import HttpResponse, HttpResponseNotFound
from django.core.mail.message import EmailMessage
from django.template import loader
from django.contrib.admin.views.decorators import staff_member_required
import time
import datetime
import urllib, urllib2
from django.conf import settings
from registration.models import RegistrationProfile
from django.utils.encoding import smart_str
import os
from django.db.models.aggregates import Sum

@settings_required
@subscription_required
def index(request):
    if settings.DEMO:
        messages.warning(request, _("You're currently using the demo version. Data are reset every %i hours. Stroke links are disabled features.") % (settings.DEMO_RESET_DELAY))

    user = request.user
    profile = user.get_profile()

    if not Proposal.objects.filter(owner=user).count():
        messages.info(request, _('How-to : create a customer, a project, a proposal and finally an invoice'))

    last_subscription = profile.get_last_subscription()
    delay_before_end_of_subscription = last_subscription.expiration_date - datetime.date.today()
    if delay_before_end_of_subscription.days <= 30:
        subscription_message = ''
        subscription_state = last_subscription.state
        if subscription_state == SUBSCRIPTION_STATE_TRIAL:
            subscription_message = _("Your trial ends in %(days)d days, if you want to keep using %(site_name)s don't forget to subscribe") % {'days': delay_before_end_of_subscription.days,
                                                                                                                                                     'site_name': Site.objects.get_current().name}
        elif subscription_state == SUBSCRIPTION_STATE_PAID:
            subscription_message = _("Your subscription ends in %(days)d days, if you want to keep using %(site_name)s don't forget to renew it") % {'days': delay_before_end_of_subscription.days,
                                                                                                                                                     'site_name': Site.objects.get_current().name}
        if subscription_message:
            messages.warning(request, subscription_message)

    today = datetime.date.today()
    one_year_back = datetime.date(today.year - 1, today.month, today.day)
    first_year = True
    if one_year_back.year >= profile.creation_date.year:
        first_year = False

    service_paid = 0
    service_waiting = 0
    service_to_be_invoiced = 0
    service_limit = 0
    service_paid_previous_year = 0
    service_limit_previous_year = 0
    service_remaining = 0

    paid = Invoice.objects.get_paid_sales(owner=user)

    if not first_year:
        paid_previous_year = Invoice.objects.get_paid_sales(owner=user,
                                                            reference_date=datetime.date(one_year_back.year, 12, 31))
    waiting = Invoice.objects.get_waiting_payments(owner=user)
    to_be_invoiced = Invoice.objects.get_to_be_invoiced(owner=user)
    limit = profile.get_sales_limit()
    remaining = limit - paid - waiting - to_be_invoiced
    sales_limit = profile.get_sales_limit()
    sales_limit2 = profile.get_sales_limit2()

    if user.get_profile().activity == AUTOENTREPRENEUR_ACTIVITY_PRODUCT_SALE_BIC:
        service_waiting = Invoice.objects.get_waiting_service_payments(owner=user)
        service_to_be_invoiced = Invoice.objects.get_service_to_be_invoiced(owner=user)
        service_limit = profile.get_service_sales_limit()
        service_paid = Invoice.objects.get_paid_service_sales(owner=user)
        service_remaining = service_limit - service_paid - service_waiting - service_to_be_invoiced
    if not first_year:
        limit_previous_year = profile.get_sales_limit(year=one_year_back.year)
        if user.get_profile().activity == AUTOENTREPRENEUR_ACTIVITY_PRODUCT_SALE_BIC:
            service_limit_previous_year = profile.get_service_sales_limit(year=one_year_back.year)
            service_paid_previous_year = Invoice.objects.get_paid_service_sales(owner=user, year=one_year_back.year)

    if not first_year and paid_previous_year > limit_previous_year:
        messages.warning(request, _('You will leave the Auto-entrepreneur status at the end of the current year.'))
        if profile.creation_help:
            messages.warning(request, _('You lose tax rates associated with creation help for overrunning sales.'))
        if profile.freeing_tax_payment:
            messages.warning(request, _('You lose freeing tax payment.'))
    else:
        if paid > sales_limit:
            if paid > sales_limit2:
                messages.warning(request, _('You will leave the Auto-entrepreneur status at the end of the current year.'))
            else:
                messages.warning(request, _('You will leave the Auto-entrepreneur status at the end of the next year.'))
            if profile.creation_help:
                messages.warning(request, _('You lose tax rates associated with creation help for overrunning sales.'))
            if profile.freeing_tax_payment:
                messages.warning(request, _('You lose freeing tax payment.'))
        elif remaining < 0:
            if remaining < (sales_limit - sales_limit2):
                messages.warning(request, _('Attention, you will leave the Auto-entrepreneur status at the end of the current year if all your proposals and invoices are paid before the end of the year.'))
            else:
                messages.warning(request, _('Attention, you will leave the Auto-entrepreneur status at the end of the next year if all your proposals and invoices are paid before the end of the year.'))
            if profile.creation_help:
                messages.warning(request, _('Attention, you will lose tax rates associated with creation help for overrunning sales if all your proposals and invoices are paid before the end of the year.'))
            if profile.freeing_tax_payment:
                messages.warning(request, _('Attention, you will lose freeing tax payment if all your proposals and invoices are paid before the end of the year.'))

    if remaining < (sales_limit - sales_limit2):
        messages.warning(request, _('You have to declare VAT from the first month of overrun.'))

    late_invoices = Invoice.objects.get_late_invoices(owner=user)
    invoices_to_send = Invoice.objects.get_invoices_to_send(owner=user)
    potential = Proposal.objects.get_potential_sales(owner=user)
    duration = Proposal.objects.get_potential_duration(owner=user)
    proposals_to_send = Proposal.objects.get_proposals_to_send(owner=user)

    min_date = Invoice.objects.get_first_invoice_paid_date(owner=user)
    if not min_date:
        chart_begin_date = today
    elif min_date < one_year_back:
        chart_begin_date = one_year_back
    else:
        chart_begin_date = min_date
    invoices = Invoice.objects.get_paid_invoices(user, begin_date=chart_begin_date)
    sales_progression = []
    last = 0.0
    for invoice in invoices:
        amount = last + float(invoice.amount)
        sales_progression.append([int(time.mktime(invoice.paid_date.timetuple())*1000), last])
        sales_progression.append([int(time.mktime(invoice.paid_date.timetuple())*1000), amount])
        last = amount

    sales_progression.append([int(time.mktime(today.timetuple())*1000), last])

    waiting_progression = []
    waiting_progression.append([int(time.mktime(today.timetuple())*1000), last])
    waiting_invoices = Invoice.objects.get_waiting_invoices(owner=user)
    for invoice in waiting_invoices:
        amount = last + float(invoice.amount)
        payment_date = invoice.payment_date
        if payment_date < today:
            payment_date = today
        waiting_progression.append([int(time.mktime(payment_date.timetuple())*1000), last])
        waiting_progression.append([int(time.mktime(payment_date.timetuple())*1000), amount])
        last = amount

    # adding ten days to see last waiting invoice
    if waiting_progression:
        waiting_progression.append([int((waiting_progression[-1][0] + 86400 * 10 * 1000)), waiting_progression[-1][1]])

    expenses_progression = []
    last = 0.0
    for expense in Expense.objects.filter(date__gte=chart_begin_date,
                                          owner=user).order_by(('date')):
        amount = last + float(expense.amount)

templates/core/admin_dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Admin dashboard" %}{% endblock %}

{% block content %}

<div class="w_left">
  <div id="users" class="widget">
    <h2>{% trans "Users" %}</h2>
    <ul>
      {% for line in users %}
      {% if line.type == "list" %}
      <li>{{ line.label }} :
      <ul>
      {% for user in line.value %}
      <li>{{ user.email }}</li>
      {% endfor %}
      </ul>
      </li>
      {% else %}
      <li>{{ line.label }} : {{ line.value }}</li>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
  <div id="activity" class="widget">
    <h2>{% trans "Activity" %}</h2>
    <ul>
      {% for line in activity %}
      <li>{{ line.label }} : {{ line.value }}</li>
      {% endfor %}
    </ul>
  </div>
</div>

<div class="w_right">
  <div id="forecast" class="widget">
    <h2>{% trans "Forecast" %}</h2>
    <ul>
      {% for line in forecast %}
      <li>{{ line.label }} : {{ line.value }}</li>
      {% endfor %}
    </ul>
  </div>
  <div id="data" class="widget">
    <h2>{% trans "Data" %}</h2>
    <ul>
      {% for line in data %}
      <li>{{ line.label }} : {{ line.value }}</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

templates/core/charts_widget.html
{% load i18n %}
{% load arithmetictags %}

<h2>{% trans "Charts" %}</h2>
<script language="javascript" type="text/javascript">
jQuery(function () {
    var paid = [[0, {{ sales.paid }}]];
    var waiting = [[0, {{ sales.waiting }}]];
    var to_be_invoiced = [[0, {{ sales.to_be_invoiced }}]];
    var remaining = [[0, {{ sales.remaining|absolute }}]];

    jQuery.plot(jQuery("#sales-chart"), [ {label : "{% trans "Paid sales" %}", data: paid},
                                          {label : "{% trans "Waiting" %}", data: waiting},
                                          {label: "{% trans "To be invoiced" %}", data: to_be_invoiced}
                                          {% if sales.remaining >= 0 %}
                                          ,{label : "{% trans "Remaining" %}", data : remaining}
                                          {% endif %}
                                         ], {
        series: {
            stack: false,
            lines: { show: false, steps: false },
            bars: { show: true, barWidth: 0.6 }
        },
        legend: { position: 'se' },
        xaxis: {mode:"time"}
    });
});

jQuery(function () {
    var sales = {{ charts.sales_progression }};
    var waiting = {{ charts.waiting_progression }};
    var expenses = {{ charts.expenses_progression }};
    var profit = {{ charts.profit_progression }};
    jQuery.plot(jQuery("#sales-progression-chart"),
                [{label: "{% trans "Sales" %}", data: sales},
                 {label: "{% trans "Waiting" %}", data: waiting},
                 {label: "{% trans "Expenses" %}", data: expenses},
                 {label: "{% trans "Profit" %}", data: profit}],
                { xaxis: { mode: "time" } ,
                  grid: { backgroundColor: { colors: ["#fff", "#eee"] }},
                legend: { position: 'nw' }
    });

});
</script>
<div id="sales-chart" style="width:420px;height:200px;"></div>
<br/>
<div id="sales-progression-chart" style="width:420px;height:200px;"></div>

templates/core/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Dashboard" %}{% endblock %}

{% block extrahead %}
<script src="{{ MEDIA_URL }}js/jquery.scrollTo-min.js" type="text/javascript" charset="utf-8"></script>
<!--[if IE]><script language="javascript" type="text/javascript" src="{{ MEDIA_URL }}js/flot/excanvas.min.js"></script><![endif]-->
<script type="text/javascript" src="{{ MEDIA_URL }}js/flot/jquery.flot.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/flot/jquery.flot.stack.js"></script>

<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery('.announcement').hide();

    var remove_prev_element = function(el){
        jQuery(el).fadeOut(500,function(){
            jQuery(this).remove();
            announcement_animation('.announcement:first');
        });
    };

    var announcement_animation = function(el){
        var element = el;
        jQuery(element).fadeIn(1000, function(){
            var lines = jQuery(this).html().match(/<br>/ig);
            var line_count = 1;
            if (lines) {
                line_count = lines.length;
            }
            var average_line_length = jQuery(this).html().length/line_count;
            var slowdown_factor = average_line_length / 50;
            jQuery(this).scrollTo('max', line_count*1200 * slowdown_factor, {
                easing:'linear',
                onAfter: function(){
                    var cloned_element = jQuery(element).clone()
                    jQuery(cloned_element).insertAfter('.announcement:last');
                    jQuery(cloned_element).hide('slow', function(){
                        setTimeout(function(){remove_prev_element(element)},3000);
                    });
            }});
        });
    };

    announcement_animation(jQuery('.announcement:first'));
});
</script>
{% endblock %}

{% block content %}

<div class="w_left">
<div id="sales" class="widget">{% include "core/sales_widget.html" %}</div>
<div id="taxes" class="widget">{% include "core/taxes_widget.html" %}</div>
<div id="invoices" class="widget">{% include "core/invoices_widget.html" %}</div>
<div id="prospects" class="widget">{% include "core/prospects_widget.html" %}</div>
</div>

<div class="w_right">
{% if announcements %}
<div class="widget">
<h2>{% trans "Info" %}</h2>
    <div  id="announcements">
    {% for announcement in announcements %}
    <div class="announcement">{% autoescape off %}{{ announcement.content|linebreaksbr }}{% endautoescape %}</div>
    {% endfor %}
    </div>
</div>
{% endif %}
<div id="charts" class="widget">{% include "core/charts_widget.html" %}</div>
</div>
{% endblock %}

templates/core/invoices_widget.html
{% load i18n %}

<h2>{% trans "Invoices" %}</h2>
<div>{% trans "Waiting payments" %} : {{ sales.waiting }}</div>
<div>{% trans "Late invoices" %} : {% autoescape off %}{{ invoices.late|default:""|join:", " }}{% endautoescape %}</div>
<div>{% trans "Invoices to send" %} : {% autoescape off %}{{ invoices.to_send|default:""|join:", " }}{% endautoescape %}</div>

templates/core/paypal_ipn.html
OK

templates/core/prospects_widget.html
{% load i18n %}

<h2>{% trans "Prospects" %}</h2>
<div>{% trans "Potential sales" %} : {% blocktrans with prospects.potential_sales as potential_sales and prospects.percentage_of_remaining|floatformat:0 as percentage_of_remaining %}{{ potential_sales }} ({{ percentage_of_remaining }}% of remaining){% endblocktrans %}</div>
<div>{% trans "Potential duration" %} : {{ prospects.duration }}</div>
<div>{% trans "Average unit price" %} : {{ prospects.average_unit_price|floatformat:0 }}</div>
<div>{% trans "Proposals to send" %} : <ul>
{% for proposal in prospects.proposals_to_send %}
    <li><a href="{% url proposal_detail proposal.id %}">{{ proposal }}</a></li>
{% endfor %}
</div>

templates/core/resend_activation_email.html
{% extends "unregistered_base.html" %}
{% load i18n %}

{% block title %}{% trans "Re-send activation email" %}{% endblock %}

{% block content %}

<h1>{% trans "Re-send activation email" %}</h1>

<p>{% trans "You have not received the activation email ? First check your emails, it may have been incorrectly classified as spam." %}</p>

<form action="" method="post">{% csrf_token %}
{{ form.email.errors }}
<p><label for="id_email">{% trans 'E-mail address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Resend activation email' %}" /></p>
</form>
{% endblock %}

templates/core/sales_widget.html
{% load i18n %}
{% load arithmetictags %}

<script language="javascript" type="text/javascript">
jQuery(document).ready(function(){
    var show_current_year = function(e){
        e.preventDefault();
        jQuery('#show_previous_year').html('<a href="#">' + jQuery('#show_previous_year').text() + '</a>');
        jQuery('#show_current_year').html('<strong>' + jQuery('#show_current_year').text() + '</strong>');
        jQuery('#current_year').show();
        jQuery('#previous_year').hide();
    };

    var show_previous_year = function(e){
        e.preventDefault();
        jQuery('#show_current_year').html('<a href="#">' + jQuery('#show_current_year').text() + '</a>');
        jQuery('#show_previous_year').html('<strong>' + jQuery('#show_previous_year').text() + '</strong>');
        jQuery('#previous_year').show();
        jQuery('#current_year').hide();
    };

    jQuery('#show_current_year').click(show_current_year);
    jQuery('#show_previous_year').click(show_previous_year);
    jQuery('#show_current_year').click();
});
</script>

<h2>{% trans "Sales" %}</h2>
{% if sales_previous_year %}
<span id="show_current_year">{{ years.0 }}</span>
&nbsp;-&nbsp;
<span id="show_previous_year">{{ years.1 }}</span>
{% endif %}
<div id="current_year">
    <div>{% trans "Paid sales" %} : {{ sales.paid }}{% if sales.service_paid %} {% blocktrans with sales.service_paid as service_paid %}(including {{ service_paid }} of service){% endblocktrans %}{% endif %}</div>
    <div>{% trans "Waiting payments" %} : {{ sales.waiting }}{% if sales.service_waiting %} {% blocktrans with sales.service_waiting as service_waiting %}(including {{ service_waiting }} of service){% endblocktrans %}{% endif %}</div>
    <div>{% trans "To be invoiced" %} : {{ sales.to_be_invoiced }}{% if sales.service_to_be_invoiced %} {% blocktrans with sales.service_to_be_invoiced as service_to_be_invoiced %}(including {{ service_to_be_invoiced }} of service){% endblocktrans %}{% endif %}</div>
    <div>{% trans "Total" %} : {{ sales.total }}{% if sales.service_total %} {% blocktrans with sales.service_total as service_total %}(including {{ service_total }} of service){% endblocktrans %}{% endif %}</div>
    {% if sales.remaining >= 0 %}
    <div>{% trans "Remaining" %} : {{ sales.remaining }}{% if sales.service_remaining %} {% blocktrans with sales.service_remaining as service_remaining %}(including {{ service_remaining }} of service){% endblocktrans %}{% endif %}</div>
    {% else %}
    <div class="overrun">{% trans "Overrun" %} : {{ sales.remaining|absolute }}</div>
    {% endif %}
    <div>{% trans "Limit" %} : {{ sales.limit }}{% if sales.service_limit %} {% blocktrans with sales.service_limit as service_limit %}(including {{ service_limit }} of service){% endblocktrans %}{% endif %}</div>
</div>
{% if sales_previous_year %}
<div id="previous_year">
    <div>{% trans "Paid sales" %} : {{ sales_previous_year.paid }}{% if sales_previous_year.service_paid %} {% blocktrans with sales_previous_year.service_paid as service_paid %}(including {{ service_paid }} of service){% endblocktrans %}{% endif %}</div>
    {% if sales_previous_year.remaining >= 0 %}
    <div>{% trans "Remaining" %} : {{ sales_previous_year.remaining }}{% if sales_previous_year.service_remaining %} {% blocktrans with sales_previous_year.service_remaining as service_remaining %}(including {{ service_remaining }} of service){% endblocktrans %}{% endif %}</div>
    {% else %}
    <div class="overrun">{% trans "Overrun" %} : {{ sales_previous_year.remaining|absolute }}</div>
    {% endif %}
    <div>{% trans "Limit" %} : {{ sales_previous_year.limit }}{% if sales_previous_year.service_limit %} {% blocktrans with sales_previous_year.service_limit as service_limit %}(including {{ service_limit }} of service){% endblocktrans %}{% endif %}</div>
</div>
{% endif %}

templates/core/subscription_expire_email_subject.html
Votre abonnement à {{ site.name }} expire dans {{ days }} jour{% if days > 1 %}s{% endif %}

templates/core/subscription_paid.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div id="confirmation-message">
{% url subscribe as url_subscribe %}
{% blocktrans with url_subscribe as url_subscribe %}
Your payment is being processed. It may take a few minutes to complete. Go back to <a href="{{ url_subscribe }}">My subscription</a> to watch the state.
{% endblocktrans %}
</div>
{% endblock %}

templates/core/subscription_paid_email_subject.html
Paiement de votre abonnement sur {{ site_name }}

templates/core/trial_expire_email.html
Votre période d'essai expire dans {{ days }} jour{% if days > 1 %}s{% endif %}.

Passé ce délai, vous ne pourrez plus accéder à l'application à moins de vous abonner en vous rendant sur https://{{ site }}{% url subscribe %}.

Si vous ne souhaitez plus utiliser l'application, vous pouvez vous désinscrire sur cette même page, vos données seront alors supprimées dans les 7 jours. Si vous laissez votre compte en l'état, vous pourrez à tout moment souscrire un abonnement et y accéder à nouveau. Cependant, si vous ne souscrivez pas d'abonnement, votre compte sera supprimé définitivement au bout d'un an.

L'équipe {{ site.name }}