urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
from django.conf import settings
from core.views import resend_activation_email, contact_us
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    url(regex=r'^$',
        view='core.views.index',
        name='index'),
    url(regex=r'^contact_us/$',
        view=contact_us,
        name='contact_us'),
    url(regex=r'^contact/sent/$',
        view='django.views.generic.simple.direct_to_template',
        name='message_sent',
        kwargs={'template': 'core/message_sent.html'}),
    url(regex=r'^logout/$',
        view='django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/'}),
    url(regex=r'^resend_activation_email/$',
        view=resend_activation_email,
        name='resend_activation_email'),
    url(regex=r'^tos/$',
        view='django.views.generic.simple.direct_to_template',
        name='tos',
        kwargs={'template': 'tos.html'}),
    url(regex=r'^changelog/$',
        view='django.views.generic.simple.direct_to_template',
        name='changelog',
        kwargs={'template': 'changelog.html'}),
    url(r'^home/', include('core.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^issues/', include('bugtracker.urls')),
    url(r'^user/', include('registration_urls')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^backup/', include('backup.urls')),
    url(r'^faq/', include('faq.urls')),
    url(r'^forum/', include('forum.urls')),


)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

faq/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Category(models.Model):
    label = models.CharField(max_length=255, verbose_name=_('Label'))
    order = models.IntegerField(default=0, verbose_name=_('Order'))

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.label

class QuestionAnswer(models.Model):
    question = models.TextField(verbose_name=_('Question'))
    answer = models.TextField(verbose_name=_('Answer'))
    category = models.ForeignKey(Category, verbose_name=_('Category'), related_name='questions')
    order = models.IntegerField(default=0, verbose_name=_('Order'))

    class Meta:
        ordering = ['category', 'order']

    def __unicode__(self):
        return self.question

templates/message/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load modeltags %}

{% block context_menu %}
<div><a href="{% url message_list %}">{% trans "Back to list" %}</a></div>
{% endblock %}

{% block content %}
<fieldset class="module aligned">
    {% with issue as object %}
    <div class="detail-row">
      <div>
      <label>{% trans "Author" %} :</label> {% if user.is_superuser and issue.owner %}<a href="{% url admin:auth_user_change issue.owner.pk %}">{% endif %}{{ issue.owner|display_name }}{% if user.is_superuser %}</a>{% endif %}
      </div>
    </div>
    <div class="detail-row">
      <div>
      <label>{{ issue|verbose_name:"category" }} :</label> {{ issue.get_category_display }}
      </div>
    </div>
    {% with "update_date" as name %}
    {% include "detail_field.html" %}
    {% endwith %}
    {% with "subject" as name %}
    {% include "detail_multiline_field.html" %}
    {% endwith %}
    {% with "message" as name %}
    {% include "detail_multiline_field.html" %}
    {% endwith %}
    {% endwith %}
</fieldset>

<h1>{% trans "Comments" %}</h1>
{% if issue.comment_set.all %}
<div class="search-list">
    <table>
        <thead>
            <tr>
                <th class="author-col">{% trans "Author" %}</th>
                <th class="date-col">{% trans "Update date" %}</th>
                <th>{% trans "Message" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in issue.comment_set.all %}
           <tr class="{% cycle 'row1' 'row2' %}">
                <td>{{ comment.owner|display_name }}</td>
                <td>{{ comment.update_date }}</td>
                <td>{{ comment.message|linebreaksbr }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div>{% trans "No comments" %}</div>
{% endif %}

<h1>{% trans "Comment" %}</h1>
<form action="{% url message_add issue_id=issue.id %}" method="post" id="comment-add-form">
    {% csrf_token %}
    <fieldset class="module aligned">
    {% with commentForm as form %}
    {% include "form.html" %}
    {% endwith %}
    </fieldset>
    <div class="submit-row">
    <input class="default" type="submit" name="action" value="{% trans "Send" %}" />
    </div>
</form>
{% endblock %}

templates/message/list.html
{% extends "base.html" %}
{% load i18n %}
{% load modeltags %}

{% block context_menu %}
<div><a href="{% url issue_add %}">{% trans "Send a message" %}</a></div>
{% endblock %}

{% block content %}
{% if issues %}
<div class="search-list">
    <table>
        <thead>
            <tr>
                <th>{% trans "Subject" %}</th>
                {% if user.is_superuser %}
                <th>{% trans "Author" %}</th>
                {% endif %}
                <th>{% trans "Update date" %}</th>
                <th>{% trans "Category" %}</th>
                <th>{% trans "Comments" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for issue in issues %}
           <tr class="{% cycle 'row2' 'row1' %} row{% if issue.is_open %} unread{% endif %}">
                <td><a href="{% url message_detail id=issue.id %}">{{ issue.subject }}</a></td>
                {% if user.is_superuser %}
                <td><a href="{% url message_detail id=issue.id %}">{{ issue.owner|display_name }}</a></td>
                {% endif %}
                <td><a href="{% url message_detail id=issue.id %}">{{ issue.update_date }}</a></td>
                <td><a href="{% url message_detail id=issue.id %}">{{ issue.get_category_display }}</a></td>
                <td><a href="{% url message_detail id=issue.id %}">{{ issue.comment_set.count }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div>{% trans "No messages" %}</div>
{% endif %}
{% endblock %}